### ISSUE TITLE
Recent update to all pip packages broke nvim-ipy

### ISSUE THREAD

**Issue by gilgameshskytrooper** [bfredl/nvim-ipy#37]
Thanks for the previous fix.

However, I unfortunately seemed to have broken `nvim-ipy` after updating all my global packages.

The error starts when I first start `IPython`:

```
error caught while executing async callback:
AttributeError("'NoneType' object has no attribute 'ioloop'",)
Traceback (most recent call last):
  File "/Users/andrewlee/.cache/vimfiles/repos/github.com/bfredl/nvim-ipy/rplugin/python3/nvim_ipy/__init__.py", line 227, in connect
    self.ip_app.initialize(Async(self), argv)
  File "/Users/andrewlee/.cache/vimfiles/repos/github.com/bfredl/nvim-ipy/rplugin/python3/nvim_ipy/__init__.py", line 74, in initialize
    JupyterConsoleApp.initialize(self, argv)
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/consoleapp.py", line 335, in initialize
    self.init_kernel_client()
  File "/Users/andrewlee/.cache/vimfiles/repos/github.com/bfredl/nvim-ipy/rplugin/python3/nvim_ipy/__init__.py", line 65, in init_kernel_client
    self.kernel_client.shell_channel.call_handlers = self.target.on_shell_msg
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/threaded.py", line 229, in ioloop
    return self.ioloop_thread.ioloop
AttributeError: 'NoneType' object has no attribute 'ioloop'

the call was requested at
  File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 168, in filter_request_cb
    result = request_cb(name, args)
  File "/usr/local/lib/python3.6/site-packages/neovim/plugin/host.py", line 91, in _on_request
    rv = handler(*args)
  File "/usr/local/lib/python3.6/site-packages/neovim/plugin/host.py", line 69, in _wrap_function
    return fn(*args)
  File "/Users/andrewlee/.cache/vimfiles/repos/github.com/bfredl/nvim-ipy/rplugin/python3/nvim_ipy/__init__.py", line 299, in ipy_connect
    Async(self).connect(args)
```

**Comment by bfredl** [comment]
It's likely a change to jupyter_client package (I never figured a distinction between external and internal API, I just used what I needed), I will need to investigate.

**Comment by gilgameshskytrooper** [comment]
What version of jupyter is stable to use?

**Comment by gilgameshskytrooper** [comment]
I am currently using jupyter version 1.0.0
`pip3 show jupyter`
```
Name: jupyter
Version: 1.0.0
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD
Location: /usr/local/lib/python3.6/site-packages
Requires: ipykernel, notebook, jupyter-console, qtconsole, ipywidgets, nbconvert
```

**Comment by gilgameshskytrooper** [comment]
Also, it doesn't look like Jupyter has been updated in a really long time.

![img](https://78.media.tumblr.com/075a3a5006d705b3b6bdedd05c66cab3/tumblr_p5js22NUBD1s5a4bko1_1280.png)

**Comment by gilgameshskytrooper** [comment]
Actually, my guess is that the error is in IPython which is caused by a change in the way [tornado handles async](https://github.com/ipython/ipython/issues/8374).

Still can't figure out why I'm getting an error tho.

**Comment by bfredl** [comment]
"jupyter 1.0.0" is a metapackage, the relevant package as I mentioned is jupyter_client. Not sure if tornado is involved, the client is iirc an API around pyzmq.

**Comment by gisochre** [comment]
After downgrading jupyter_client to 5.2.0 the issue goes away. 
```
$ pip show jupyter_client
Name: jupyter-client
Version: 5.2.0
Summary: Jupyter protocol implementation and client libraries
Home-page: https://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /home/sysmanj/.pyenv/versions/3.6.4/envs/neovim3/lib/python3.6/site-packages
Requires: traitlets, jupyter-core, python-dateutil, pyzmq, pytest
```
Don't know, why current issue was closed tho.
