### ISSUE TITLE
E117: Unknown function: IPyConnect

### ISSUE THREAD

**Issue by Joellidin** [bfredl/nvim-ipy#47]
Like some other issues I get this error:
```
E117: Unknown function: IPyConnect
```

When writing `:UpdateRemotePlugins` I get the following error:
```
Encountered ModuleNotFoundError loading plugin at /Users/joellidin/.vim/plugged/nvim-ipy/rplugin/python3/nvim_ipy: No module named 'jupyter_client'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/host.py", line 145, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
ModuleNotFoundError: No module named 'jupyter_client'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /Users/joellidin/.local/share/nvim/rplugin.vim
```

I have the following version of jupyter:
```
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
```

My Neovim version is `NVIM v0.4.0-dev`

# EDIT
The problem was in my `.vimrc` and `:python3_host_prog`

**Comment by RobsonLana** [comment]
What exactly was the problem?
