### ISSUE TITLE
Signature mismatch

### ISSUE THREAD

**Issue by rsdenijs** [bfredl/nvim-ipy#8]
I can create a new seesion using :IPython (yay!) however, when creating a kernel using `ipython kernel` on the same machine and then using `:IPython --existing kerne` to communicate from my vim session the communication fails because of a signature mismatch

[Output from the actual kernel]
````
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/cross/local/lib/python2.7/site-packages/IPython/kernel/zmq/kernelbase.py", line 175, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "/home/ubuntu/.virtualenvs/cross/local/lib/python2.7/site-packages/IPython/kernel/zmq/session.py", line 836, in deserialize
    raise ValueError("Invalid Signature: %r" % signature)
ValueError: Invalid Signature: '51a7d95d58ae497bfb01d4d757d6f978585e9a543140d9d71d7d4ec51fdf7ecf'
````
I get the same error regardless of starting vim and the kernel in a virtualenv outside.

I can connect to the kernel using `ipython console --existing kernel-XXXX.json`
What can be happening here?

**Comment by bfredl** [comment]
Can comfirm, will look into it tomorrow maybe.

**Comment by languitar** [comment]
Same thing here.

**Comment by Maltimore** [comment]
Me too..

**Comment by jorgesca** [comment]
Hi, I am having exactly the same issue. Any progress so far? I usually create a new session with `:IPython` but I wanted to try a few things directly in the console...

**Comment by jorgesca** [comment]
As a workaround, one can start a kernel with nvim-ipy, then use the %connect_info magic info to start the console|qtconsole|notebook

**Comment by dmos62** [comment]
Same here, cannot connect to a running kernel. This makes this unusable for me because I'm working with remote kernels, i.e. local kernels are not useful to me.

**Comment by michaelfsp** [comment]
same problem here.

**Comment by dajuno** [comment]
+1. Initial post was 1 year ago though

**Comment by bfredl** [comment]
Sorry for the delay, this was a very subtle change in the initialization of ConsoleApp between IPython 3.x and Jupyter 4.x (but I don't understand why it only affected `--existing` and didn't make the plugin completely unusable...). Please try latest version.

**Comment by jorgesca** [comment]
I tried today with current version and jupyter console 5.1.0 and it seems to be working back again. Thanks
